name: Commit Lint

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  commit_check:
    name: Check Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gold-standard-phantoms/github-actions/.github/actions/commit-check@v0.3.0
